Update install-php-extensions

diff --git a/services/php/extensions/install-php-extensions b/services/php/extensions/install-php-extensions
--- a/services/php/extensions/install-php-extensions
+++ b/services/php/extensions/install-php-extensions
@@ -17,6 +17,35 @@ if ! which docker-php-ext-configure >/dev/null || ! which docker-php-ext-enable 
 	exit 1
 fi
 
+IPE_VERSION=master
+
+if test "$IPE_VERSION" = master && test "${CI:-}" != true; then
+	cat <<EOF
+
+#############################################################################################################
+#                                                                                                           #
+#                                            W A R N I N G ! ! !                                            #
+#                                                                                                           #
+# You are using an unsupported method to get install-php-extensions!                                        #
+#                                                                                                           #
+# Please update the way you fetch it. Read the instrictions at                                              #
+# https://github.com/mlocati/docker-php-extension-installer#usage                                           #
+#                                                                                                           #
+# For example, if you get this script by fetching                                                           #
+# https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions    #
+# replace it with                                                                                           #
+# https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions #
+#                                                                                                           #
+# Sleeping for a while so you get bored of this and act ;)                                                  #
+#                                                                                                           #
+#############################################################################################################
+
+EOF
+	sleep 10 || true
+else
+	printf 'install-php-extensions v.%s\n' "$IPE_VERSION"
+fi
+
 # Reset the Internal Field Separator
 resetIFS() {
 	IFS='	 
@@ -94,9 +123,28 @@ normalizePHPModuleName() {
 	printf '%s' "$normalizePHPModuleName_name"
 }
 
+# Get the PECL name of PHP extension
+#
+# Arguments:
+#   $1: the name of the extension
+#
+# Output:
+#   The PECL name of the extension
+getPeclModuleName() {
+	normalizePHPModuleName_name="$1"
+	case "$normalizePHPModuleName_name" in
+		http)
+			normalizePHPModuleName_name=pecl_http
+			;;
+	esac
+	printf '%s' "$normalizePHPModuleName_name"
+}
+
 # Parse a module name (and optionally version) as received via command arguments, extracting the version and normalizing it
-# Example:
+# Examples:
 #   xdebug-2.9.8
+#   xdebug-^2
+#   xdebug-^2.9
 #
 # Arguments:
 #   $1: the name of the module to be normalized
@@ -141,6 +189,56 @@ getWantedPHPModuleVersion() {
 	elif printf '%s' "$1" | grep -Eq '^@[a-zA-Z0-9_]+$'; then
 		eval printf '%s' "\${PHP_WANTEDMODULEVERSION__${1#@}:-}"
 	fi
+}
+
+# Get the wanted PHP module version, resolving it if it starts with '^'
+#
+# Arguments:
+#   $1: the name of the module to be normalized
+#
+# Output:
+#   The version to be used
+resolveWantedPHPModuleVersion() {
+	resolveWantedPHPModuleVersion_raw="$(getWantedPHPModuleVersion "$1")"
+	resolveWantedPHPModuleVersion_afterCaret="${resolveWantedPHPModuleVersion_raw#^}"
+	if test "$resolveWantedPHPModuleVersion_raw" = "$resolveWantedPHPModuleVersion_afterCaret"; then
+		printf '%s' "$resolveWantedPHPModuleVersion_raw"
+		return
+	fi
+	resolveWantedPHPModuleVersion_xml="$(curl -sSLf "http://pecl.php.net/rest/r/$1/allreleases.xml")"
+	resolveWantedPHPModuleVersion_versions="$(printf '%s' "$resolveWantedPHPModuleVersion_xml" | tr -s ' \t\r\n' ' ' | sed -r 's# *<#\n<#g' | grep '<v>' | sed 's#<v>##g' | sed 's# ##g')"
+	resetIFS
+	for resolveWantedPHPModuleVersion_version in $resolveWantedPHPModuleVersion_versions; do
+		resolveWantedPHPModuleVersion_suffix="${resolveWantedPHPModuleVersion_version#$resolveWantedPHPModuleVersion_afterCaret}"
+		if test "$resolveWantedPHPModuleVersion_version" != "${resolveWantedPHPModuleVersion_version#$resolveWantedPHPModuleVersion_afterCaret.}"; then
+			# Example: looking for 1.0, found 1.0.1
+			printf '%s' "$resolveWantedPHPModuleVersion_version"
+			return
+		fi
+	done
+	for resolveWantedPHPModuleVersion_version in $resolveWantedPHPModuleVersion_versions; do
+		resolveWantedPHPModuleVersion_suffix="${resolveWantedPHPModuleVersion_version#$resolveWantedPHPModuleVersion_afterCaret}"
+		if test "$resolveWantedPHPModuleVersion_version" = "$resolveWantedPHPModuleVersion_suffix"; then
+			continue
+		fi
+		if test -z "$resolveWantedPHPModuleVersion_suffix"; then
+			# Example: looking for 1.0, found exactly it
+			printf '%s' "$resolveWantedPHPModuleVersion_version"
+			return
+		fi
+		case "$resolveWantedPHPModuleVersion_suffix" in
+			[0-9])
+				# Example: looking for 1.1, but this is 1.10
+				;;
+			*)
+				# Example: looking for 1.1, this is 1.1rc1
+				printf '%s' "$resolveWantedPHPModuleVersion_version"
+				return
+				;;
+		esac
+	done
+	printf 'Unable to find a version of "%s" compatible with "%s"\nAvailable versions are:\n%s\n' "$1" "$resolveWantedPHPModuleVersion_raw" "$resolveWantedPHPModuleVersion_versions" >&2
+	exit 1
 }
 
 # Set these variables:
@@ -408,6 +506,14 @@ buildRequiredPackageLists() {
 					buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libwebp-dev"
 				fi
 				;;
+			gearman@alpine)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++ libuuid"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile boost-dev gperf libmemcached-dev libevent-dev util-linux-dev"
+				;;
+			gearman@debian)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libgearman[0-9]*$"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libgearman-dev"
+				;;
 			gettext@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libintl"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile gettext-dev"
@@ -630,14 +736,6 @@ buildRequiredPackageLists() {
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libpq5"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libpq-dev"
 				;;
-			pdo_sqlsrv@alpine)
-				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++ unixodbc"
-				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile unixodbc-dev"
-				;;
-			pdo_sqlsrv@debian)
-				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libodbc1 odbcinst"
-				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile unixodbc-dev"
-				;;
 			pgsql@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent postgresql-libs"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile postgresql-dev"
@@ -735,13 +833,16 @@ buildRequiredPackageLists() {
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libcurl3-gnutls"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libcurl4-gnutls-dev libxml2-dev"
 				;;
-			sqlsrv@alpine)
+			sqlsrv@alpine | pdo_sqlsrv@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++ unixodbc"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile unixodbc-dev"
 				;;
-			sqlsrv@debian)
+			sqlsrv@debian | pdo_sqlsrv@debian)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent unixodbc"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile unixodbc-dev"
+				if ! isMicrosoftSqlServerODBCInstalled; then
+					buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile gnupg apt-transport-https"
+				fi
 				;;
 			ssh2@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libssh2"
@@ -1001,10 +1102,12 @@ setTargetTriplet() {
 #   The number of processors to be used
 getCompilationProcessorCount() {
 	case "$1" in
-		amqp | bcmath | bz2 | calendar | exif | gd | gettext | grpc | imagick | intl | mysqli | opcache | pcntl | pdo_mysql | protobuf | redis | soap | sockets | tidy | xdebug | xsl | yaml | zip)
+		amqp | bcmath | bz2 | calendar | exif | gd | gettext | grpc | http | imagick | intl | mysqli | opcache | pcntl | pdo_mysql | protobuf | redis | soap | sockets | tidy | xdebug | xsl | yaml | zip)
+			# These extensions support parallel compilation
 			getProcessorCount
 			;;
 		*)
+			# We don't know - it's safer to disable parallel compilation
 			echo 1
 			;;
 	esac
@@ -1133,9 +1236,45 @@ installOracleInstantClient() {
 	esac
 }
 
+# Check if the Microsoft SQL Server ODBC Driver is installed
+#
+# Return:
+#   0 (true): if the string is in the list
+#   1 (false): if the string is not in the list
+isMicrosoftSqlServerODBCInstalled() {
+	test -d /opt/microsoft/msodbcsql*/
+}
+
+# Install the Microsoft SQL Server ODBC Driver
+installMicrosoftSqlServerODBC() {
+	printf 'Installing the Microsoft SQL Server ODBC Driver\n'
+	case "$DISTRO" in
+		alpine)
+			# https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#alpine17
+			rm -rf /tmp/src/msodbcsql.apk
+			curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.6.1.1-1_amd64.apk
+			printf '\n' | apk add --allow-untrusted /tmp/src/msodbcsql.apk
+			rm -rf /tmp/src/msodbcsql.apk
+			;;
+		debian)
+			# https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#debian17
+			printf -- '- installing the Microsoft APT key\n'
+			curl -sSLf https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
+			if ! test -f /etc/apt/sources.list.d/mssql-release.list; then
+				printf -- '- adding the Microsoft APT source list\n'
+				curl -sSLf https://packages.microsoft.com/config/debian/$DISTRO_VERSION_NUMBER/prod.list >/etc/apt/sources.list.d/mssql-release.list
+				DEBIAN_FRONTEND=noninteractive apt-get -q update
+			fi
+			printf -- '- installing the APT package\n'
+			DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get -qy install '^msodbcsql[0-9]+$'
+			;;
+	esac
+}
+
 # Install Composer
 installComposer() {
 	installComposer_version="$(getWantedPHPModuleVersion @composer)"
+	installComposer_version="${installComposer_version#^}"
 	if test -z "$installComposer_version"; then
 		installComposer_fullname=composer
 		installComposer_flags=''
@@ -1356,7 +1495,7 @@ getPackageSource() {
 installRemoteModule() {
 	installRemoteModule_module="$1"
 	printf '### INSTALLING REMOTE MODULE %s ###\n' "$installRemoteModule_module"
-	installRemoteModule_version="$(getWantedPHPModuleVersion "$installRemoteModule_module")"
+	installRemoteModule_version="$(resolveWantedPHPModuleVersion "$installRemoteModule_module")"
 	rm -rf "$CONFIGURE_FILE"
 	installRemoteModule_manuallyInstalled=0
 	installRemoteModule_cppflags=''
@@ -1415,6 +1554,25 @@ installRemoteModule() {
 					;;
 			esac
 			;;
+		gearman)
+			if test -z "$installRemoteModule_version"; then
+				if test $PHP_MAJMIN_VERSION -le 506; then
+					installRemoteModule_version=1.1.2
+				fi
+			fi
+			case "$DISTRO" in
+				alpine)
+					if ! test -e /usr/local/include/libgearman/gearman.h || ! test -e /usr/local/lib/libgearman.so; then
+						installRemoteModule_src="$(getPackageSource https://github.com/gearman/gearmand/releases/download/1.1.19.1/gearmand-1.1.19.1.tar.gz)"
+						cd -- "$installRemoteModule_src"
+						./configure
+						make -j$(getProcessorCount) install-binPROGRAMS
+						make -j$(getProcessorCount) install-nobase_includeHEADERS
+						cd - >/dev/null
+					fi
+					;;
+			esac
+			;;
 		gmagick)
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -le 506; then
@@ -1430,12 +1588,20 @@ installRemoteModule() {
 					installRemoteModule_version=1.33.1
 				fi
 			fi
+			if test -z "$installRemoteModule_version" || test "$installRemoteModule_version" = 1.35.0; then
+				case "$DISTRO_VERSION" in
+					alpine@3.13)
+						installRemoteModule_cppflags='-Wno-maybe-uninitialized'
+						;;
+				esac
+			fi
 			;;
 		http)
-			installRemoteModule_module=pecl_http
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -le 506; then
 					installRemoteModule_version=2.6.0
+				elif test $PHP_MAJMIN_VERSION -le 704; then
+					installRemoteModule_version=3.2.4
 				fi
 			fi
 			if test $PHP_MAJMIN_VERSION -ge 700; then
@@ -1613,11 +1779,18 @@ installRemoteModule() {
 		pdo_sqlsrv | sqlsrv)
 			if test -z "$installRemoteModule_version"; then
 				# https://docs.microsoft.com/it-it/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-2017
-				if test $PHP_MAJMIN_VERSION -le 700; then
+				if test $PHP_MAJMIN_VERSION -le 506; then
+					installRemoteModule_version=3.0.1
+				elif test $PHP_MAJMIN_VERSION -le 700; then
 					installRemoteModule_version=5.3.0
 				elif test $PHP_MAJMIN_VERSION -le 701; then
 					installRemoteModule_version=5.6.1
+				elif test $PHP_MAJMIN_VERSION -le 702; then
+					installRemoteModule_version=5.8.1
 				fi
+			fi
+			if ! isMicrosoftSqlServerODBCInstalled; then
+				installMicrosoftSqlServerODBC
 			fi
 			;;
 		propro)
@@ -1701,7 +1874,7 @@ installRemoteModule() {
 					installRemoteModule_zstdVersion=1.4.4
 					installRemoteModule_zstdVersionMajor=$(echo $installRemoteModule_zstdVersion | cut -d. -f1)
 					rm -rf /tmp/src/zstd
-					mv "$(getPackageSource https://github.com/facebook/zstd/releases/download/v1.4.4/zstd-$installRemoteModule_zstdVersion.tar.gz)" /tmp/src/zstd
+					mv "$(getPackageSource https://github.com/facebook/zstd/releases/download/v$installRemoteModule_zstdVersion/zstd-$installRemoteModule_zstdVersion.tar.gz)" /tmp/src/zstd
 					cd /tmp/src/zstd
 					make V=0 -j$(getProcessorCount) lib
 					cp -f lib/libzstd.so "/usr/lib/$TARGET_TRIPLET/libzstd.so.$installRemoteModule_zstdVersion"
@@ -2024,12 +2197,8 @@ installRemoteModule() {
 				docker-php-ext-enable "$installRemoteModule_module"
 			fi
 			;;
-		pecl_http)
-			# http must be loaded after raphf and propro
-			docker-php-ext-enable --ini-name "xx-php-ext-http.ini" http
-			;;
-		memcached)
-			# memcached must be loaded after msgpack
+		http | memcached)
+			# http must be loaded after raphf and propro, memcached must be loaded after msgpack
 			docker-php-ext-enable --ini-name "xx-php-ext-$installRemoteModule_module.ini" "$installRemoteModule_module"
 			;;
 		snuffleupagus)
@@ -2043,7 +2212,6 @@ installRemoteModule() {
 }
 
 # Configure the PECL package installed
-# If we'll use pickle, the zip extension will be added to PHP_MODULES_TO_INSTALL
 #
 # Updates:
 #   PHP_MODULES_TO_INSTALL
@@ -2066,10 +2234,7 @@ configureInstaller() {
 				pecl channel-update pecl.php.net || true
 				return
 			fi
-			if ! stringInList 'zip' "$PHP_PREINSTALLED_MODULES"; then
-				PHP_MODULES_TO_INSTALL="zip $(removeStringFromList 'zip' "$PHP_MODULES_TO_INSTALL")"
-			fi
-			if anyStringInList 'swoole xdebug xhprof' "$PHP_MODULES_TO_INSTALL"; then
+			if false && anyStringInList '' "$PHP_MODULES_TO_INSTALL"; then
 				USE_PICKLE=2
 			else
 				curl -sSLf https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar -o /tmp/pickle
@@ -2125,20 +2290,21 @@ installPeclPackage() {
 	if ! test -f "$CONFIGURE_FILE"; then
 		printf '\n' >"$CONFIGURE_FILE"
 	fi
+	installPeclPackage_name="$(getPeclModuleName "$1")"
 	if test $USE_PICKLE -eq 0; then
 		if test -z "${2:-}"; then
-			installPeclPackage_fullname="$1"
+			installPeclPackage_fullname="$installPeclPackage_name"
 		else
-			installPeclPackage_fullname="$1-$2"
+			installPeclPackage_fullname="$installPeclPackage_name-$2"
 		fi
 		cat "$CONFIGURE_FILE" | MAKE="make -j$(getCompilationProcessorCount $1)" CPPFLAGS="${3:-}" pecl install "$installPeclPackage_fullname"
 	else
 		if test -z "${2:-}"; then
-			installPeclPackage_fullname="$1"
+			installPeclPackage_fullname="$installPeclPackage_name"
 		else
-			installPeclPackage_fullname="$1@$2"
+			installPeclPackage_fullname="$installPeclPackage_name@$2"
 		fi
-		MAKE="make -j$(getCompilationProcessorCount $1)" CPPFLAGS="${3:-}" /tmp/pickle install --tmp-dir=/tmp/pickle.tmp --no-interaction --with-configure-options "$CONFIGURE_FILE" -- "$installPeclPackage_fullname"
+		MAKE="make -j$(getCompilationProcessorCount $1)" CPPFLAGS="${3:-}" /tmp/pickle install --tmp-dir=/tmp/pickle.tmp --no-interaction --version-override='' --with-configure-options "$CONFIGURE_FILE" -- "$installPeclPackage_fullname"
 	fi
 }
 
