Update install-php56-extensions

diff --git a/services/php56/extensions/install-php-extensions b/services/php56/extensions/install-php-extensions
--- a/services/php56/extensions/install-php-extensions
+++ b/services/php56/extensions/install-php-extensions
@@ -1314,6 +1314,9 @@ buildRequiredPackageLists() {
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libcurl3-gnutls"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libcurl4-gnutls-dev libxml2-dev"
 				;;
+			sourceguardian@alpine)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent eudev-libs"
+				;;
 			spx@alpine)
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile zlib-dev"
 				;;
@@ -1454,6 +1457,14 @@ buildRequiredPackageLists() {
 				;;
 			wddx@debian)
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libxml2-dev"
+				;;
+			wikidiff2@alpine)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile git"
+				;;
+			wikidiff2@debian)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libthai0"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile git libthai-dev"
 				;;
 			xdebug@alpine)
 				if test $PHP_MAJMIN_VERSION -ge 800; then
@@ -2056,7 +2067,7 @@ installMicrosoftSqlServerODBC() {
 		alpine)
 			rm -rf /tmp/src/msodbcsql.apk
 			if test $PHP_MAJMIN_VERSION -le 703; then
-				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.10.5.1-1_amd64.apk
+				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.10.6.1-1_amd64.apk
 			else
 				case $(uname -m) in
 					aarch64 | arm64 | armv8)
@@ -2066,7 +2077,7 @@ installMicrosoftSqlServerODBC() {
 						installMicrosoftSqlServerODBC_arch=amd64
 						;;
 				esac
-				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.2.1-1_$installMicrosoftSqlServerODBC_arch.apk
+				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_$installMicrosoftSqlServerODBC_arch.apk
 			fi
 			printf '\n' | apk add --allow-untrusted /tmp/src/msodbcsql.apk
 			rm -rf /tmp/src/msodbcsql.apk
@@ -2229,6 +2240,59 @@ installLibMPDec() {
 	cd - >/dev/null
 }
 
+# Check if libdatrie is installed
+#
+# Return:
+#   0 (true)
+#   1 (false)
+isLibDatrieInstalled() {
+	if ! test -f /usr/local/lib/libdatrie.so && ! test -f /usr/lib/libdatrie.so && ! test -f /usr/lib/x86_64*/libdatrie.so; then
+		return 1
+	fi
+	if ! test -f /usr/local/include/datrie/trie.h && ! test -f /usr/include/datrie/trie.h; then
+		return 1
+	fi
+	return 0
+}
+
+# Install libdatrie
+installLibDatrie() {
+	printf 'Installing libdatrie\n'
+	installLibDatrie_src="$(getPackageSource https://github.com/tlwg/libdatrie/releases/download/v0.2.13/libdatrie-0.2.13.tar.xz)"
+	cd -- "$installLibDatrie_src"
+	./configure
+	make -j$(getProcessorCount)
+	make install
+	cd - >/dev/null
+}
+
+# Check if libdatrie is installed
+#
+# Return:
+#   0 (true)
+#   1 (false)
+isLibThaiInstalled() {
+	return 1
+	if ! test -f /usr/local/lib/libthai.so && ! test -f /usr/lib/libthai.so && ! test -f /usr/lib/x86_64*/libthai.so; then
+		return 1
+	fi
+	if ! test -f /usr/local/include/thai/thailib.h && ! test -f /usr/include/thai/thailib.h; then
+		return 1
+	fi
+	return 0
+}
+
+# Install libdatrie
+installLibThai() {
+	printf 'Installing libthai\n'
+	installLibThai_src="$(getPackageSource https://github.com/tlwg/libthai/releases/download/v0.1.29/libthai-0.1.29.tar.xz)"
+	cd -- "$installLibThai_src"
+	./configure
+	make -j$(getProcessorCount)
+	make install
+	cd - >/dev/null
+}
+
 # Install Composer
 installComposer() {
 	installComposer_version="$(getWantedPHPModuleVersion @composer)"
@@ -2362,6 +2426,37 @@ installCargo() {
 	if test -z "${IPE_UNINSTALL_CARGO:-}"; then
 		IPE_UNINSTALL_CARGO=y
 	fi
+}
+
+installNewRelic() {
+	printf '# Installing newrelic\n'
+	installNewRelic_search='\bnewrelic-php[0-9.]*-[0-9]+(\.[0-9]+)*-linux'
+	case "$DISTRO" in
+		alpine)
+			installNewRelic_search="$installNewRelic_search-musl"
+			;;
+	esac
+	installNewRelic_file="$(curl -sSLf -o- https://download.newrelic.com/php_agent/release/ | sed -E 's/<[^>]*>//g' | grep -Eo "$installNewRelic_search.tar.gz" | sort | head -1)"
+	installNewRelic_url="https://download.newrelic.com/php_agent/release/$installNewRelic_file"
+	installNewRelic_src="$(getPackageSource "$installNewRelic_url")"
+	cd -- "$installNewRelic_src"
+	NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_SILENT=1 ./newrelic-install install
+	case "${IPE_NEWRELIC_DAEMON:-}" in
+		1 | y* | Y*)
+			NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_SILENT=1 ./newrelic-install install_daemon
+			;;
+	esac
+	cd - >/dev/null
+	cat <<EOT
+NewRelic has been installed from $installNewRelic_url
+You may need to:
+- change the owner/permissions of /var/log/newrelic
+  (for example: chown -R www-data:www-data /var/log/newrelic)
+- set the value of the newrelic.license configuration key in
+  $PHP_INI_DIR/conf.d/newrelic.ini
+  (if you didn't set the NR_INSTALL_KEY environment variable)
+
+EOT
 }
 
 # Install a bundled PHP module given its handle
@@ -2606,13 +2701,18 @@ EOF
 			esac
 			;;
 	esac
-	php -r 'return;' >/dev/null 2>/dev/null || true
-	installBundledModule_errAfter="$(php -r 'return;' 2>&1 || true)"
-	if test "$installBundledModule_errAfter" != "$installBundledModule_errBefore"; then
-		printf 'PHP has problems after installing the "%s" extension:\n%s\n' "$1" "$installBundledModule_errAfter" >&2
-		rm "$PHP_INI_DIR/conf.d/docker-php-ext-$1.ini" || true
-		return 1
-	fi
+	case "${IPE_SKIP_CHECK:-}" in
+		1 | y* | Y*) ;;
+		*)
+			php -r 'return;' >/dev/null 2>/dev/null || true
+			installBundledModule_errAfter="$(php -r 'return;' 2>&1 || true)"
+			if test "$installBundledModule_errAfter" != "$installBundledModule_errBefore"; then
+				printf 'PHP has problems after installing the "%s" extension:\n%s\n' "$1" "$installBundledModule_errAfter" >&2
+				rm "$PHP_INI_DIR/conf.d/docker-php-ext-$1.ini" || true
+				return 1
+			fi
+			;;
+	esac
 }
 
 # Fetch a tar.gz file, extract it and returns the path of the extracted folder.
@@ -3206,6 +3306,10 @@ installRemoteModule() {
 				fi
 			fi
 			;;
+		newrelic)
+			installNewRelic
+			installRemoteModule_manuallyInstalled=2
+			;;
 		oauth)
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -le 506; then
@@ -3325,11 +3429,6 @@ installRemoteModule() {
 				addConfigureOption enable-swoole-json yes
 				# enable curl support?
 				addConfigureOption enable-swoole-curl yes
-			fi
-			;;
-		opentelemetry)
-			if test -z "$installRemoteModule_version"; then
-				installRemoteModule_version=beta
 			fi
 			;;
 		parallel)
@@ -3929,7 +4028,7 @@ installRemoteModule() {
 							installRemoteModule_architecture=alpine-arm64
 							;;
 						*)
-							installRemoteModule_architecture=alpine
+							installRemoteModule_architecture=alpine-x86_64
 							;;
 					esac
 					;;
@@ -3945,6 +4044,10 @@ installRemoteModule() {
 					;;
 			esac
 			installRemoteModule_url="$(curl -sSLf -o - https://tideways.com/profiler/downloads | grep -Eo "\"[^\"]+/tideways-php-([0-9]+\.[0-9]+\.[0-9]+)-$installRemoteModule_architecture.tar.gz\"" | cut -d'"' -f2)"
+			if test -z "$installRemoteModule_url"; then
+				echo 'Failed to find the tideways tarball to be downloaded'
+				exit 1
+			fi
 			printf 'Downloading tideways from %s\n' "$installRemoteModule_url"
 			installRemoteModule_src="$(getPackageSource $installRemoteModule_url)"
 			if test -d "$installRemoteModule_src/dist"; then
@@ -4010,6 +4113,33 @@ installRemoteModule() {
 					installRemoteModule_version=beta
 				fi
 			fi
+			;;
+		wikidiff2)
+			case "$DISTRO" in
+				alpine)
+					if ! isLibDatrieInstalled; then
+						installLibDatrie
+					fi
+					if ! isLibThaiInstalled; then
+						installLibThai
+					fi
+					;;
+			esac
+			if test -z "$installRemoteModule_version"; then
+				if test $PHP_MAJMIN_VERSION -le 702; then
+					installRemoteModule_version=1.13.0
+				else
+					installRemoteModule_version="$(git -c versionsort.suffix=- ls-remote --tags --refs --quiet --exit-code --sort=version:refname https://github.com/wikimedia/mediawiki-php-wikidiff2.git 'refs/tags/*.*.*' | tail -1 | cut -d/ -f3)"
+				fi
+			fi
+			installRemoteModule_src="$(getPackageSource "https://codeload.github.com/wikimedia/mediawiki-php-wikidiff2/tar.gz/refs/tags/$installRemoteModule_version")"
+			cd -- "$installRemoteModule_src"
+			phpize
+			./configure
+			make -j$(getProcessorCount)
+			make install
+			cd - >/dev/null
+			installRemoteModule_manuallyInstalled=1
 			;;
 		xdebug)
 			if test -z "$installRemoteModule_version"; then
@@ -4191,8 +4321,15 @@ installRemoteModule() {
 		installPeclPackage "$installRemoteModule_module" "$installRemoteModule_version" "$installRemoteModule_cppflags" "$installRemoteModule_path"
 	fi
 	postProcessModule "$installRemoteModule_module"
-	checkModuleWorking "$installRemoteModule_module" "$installRemoteModule_ini_basename" "$installRemoteModule_ini_extra"
-	enablePhpExtension "$installRemoteModule_module" "$installRemoteModule_ini_basename" "$installRemoteModule_ini_extra"
+	if test $installRemoteModule_manuallyInstalled -lt 2; then
+		case "${IPE_SKIP_CHECK:-}" in
+			1 | y* | Y*) ;;
+			*)
+				checkModuleWorking "$installRemoteModule_module" "$installRemoteModule_ini_basename" "$installRemoteModule_ini_extra"
+				;;
+		esac
+		enablePhpExtension "$installRemoteModule_module" "$installRemoteModule_ini_basename" "$installRemoteModule_ini_extra"
+	fi
 }
 
 # Check if a module/helper may be installed using the pecl archive
@@ -4458,7 +4595,7 @@ fixLetsEncrypt() {
 					invokeAptGetUpdate
 				fi
 				printf -- '- installing newer ca-certificates package\n'
-				DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends $IPE_APTGET_INSTALLOPTIONS ca-certificates
+				DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends ${IPE_APTGET_INSTALLOPTIONS:-} ca-certificates
 			fi
 			;;
 		*)
